# do not install anything extra onto the image
language: generic

# use a Mac OSX image
os: osx

# only run builds on pushes to the master branch
branches:
  only:
  - main

# decrypt the encrypted SSH key file so it can be used for scp auth in post_build.sh
#before_install:
#- openssl aes-256-cbc -k "$KEYFILE_PASS" -in "${UPLOAD_KEYPATH}.enc" -out "${UPLOAD_KEYPATH}" -d

# run the script to download and install Unity editor
install:
- sudo -E sh ./Scripts/install.sh

# run the script for unit tests and builds
script:
- sudo -E sh ./Scripts/build.sh

# run the script to upload the builds as tarballs
after_success:
- sudo -E sh ./Scripts/post_build.sh

# environment variables used in bash scripts
env:
  global:
  - UNITYCI_PROJECT_NAME="Project_Travis"
  - UPLOAD_KEYPATH="./Scripts/upload"
  - TRAVIS_TAG="Deploy-2020.3.12f1" 
  - PROJECT_NAME="Project_Travis" 
  - UNITY_PROJECT_PATH="Project_Travis" 
  - DEPLOY_UNITYPACKAGE="path set in deploy script"